sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: RaaGoXJVMPWw39aJ9Y8XuL3qAKnctDXoksE0GGuzY45CcYNwmPhVlgV0wRVbNAKcqa7qglH+7QVmfENf7/ty/QkJ8ZKk3zyPp41dYhGo7yiwu4OvaY7kBpoiT8nw7y2K3+o8pQma/GesuYRRkbfbCTlDQOUAZPi7Pd/XF+5fFHc/6zCDpxZlBV543R49ChfI1koXH3rK1N31CoFVkfXIs/zLb/R5FUL5GPKE8D8ENWaC9H5KIvxv6/5TYICiusVkEt5QYlYzthxgvylNOXCGk5Hr+W7z7D6BTo92eR1SlULgLsXW8p7o69EJD9BS6NLEOG6bB9qrZVc5VgKjjxjamf2ZxxBMTbqJVDqIkQWocXj41BJUAmx6RUa8fJfy2LO8HSwLXCM3GccFgl/ot86FAzKOr3f4ZVJCupbWnFaePxw1L2fbXyiccd7gLIkoVrCml058PpQ1WWZSEcDK+FpMpog9znwdDyuYtaPo0uqoEHX0byDbufSGLPN4Ov/v2nH14g1+vt0CXelJqAzHgKtND7+XlSL16s1aMJ35RPoIoU+6Yttp1QHptwrC6kF8moWcG+sKRh/1yo8C0YSvGNrrd1aGqxY7KNeR85I1Lu5tQ3M+znQ7RSesH8M3/2PeVkChj2wBP4KmtMdltCWzUBl8u806ncWCBaYZUiDV6/W+yl4=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Ancient-Allan_5746
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy